export const CHANNEL_TYPES = {
  DRIBBLE: 'DRIBBLE',
  GITHUB: 'GITHUB',
  INSTAGRAM: 'INSTAGRAM',
  LINKEDIN: 'LINKEDIN',
  TELEGRAM: 'TELEGRAM',
  TWITTER: 'TWITTER',
  WEBSITE: 'WEBSITE',
  YOUTUBE: 'YOUTUBE',
  AMAZON: 'AMAZON',
  OTHER: 'OTHER',
};

export const BLURBS = {
  HENRICH: 'HENRICH',
  ARMSTRONG: 'ARMSTRONG',
  SYED: 'SYED',
  MORRIS: 'MORRIS',
  GELFAND: 'GELFAND',
  FRANKOPAN: 'FRANKOPAN',
  RIDLEY: 'RIDLEY',
  MCAFEE: 'MCAFEE',
  KLITGAARD: 'KLITGAARD',
  HALL: 'HALL',
  YOELI: 'YOELI',
  HOFFMAN: 'HOFFMAN',
  HEYWOOD: 'HEYWOOD',
  BODANIS: 'BODANIS',
};

